CUDNN_BENCHMARK: true
SEED: 42
OUTPUT_DIR: ""

GLOBAL:
  HACK: 1.0

DATALOADER:
  ASPECT_RATIO_GROUPING: true
  FILTER_EMPTY_ANNOTATIONS: true
  NUM_WORKERS: 4
  REPEAT_THRESHOLD: 0.0
  SAMPLER_TRAIN: TrainingSampler

DATASETS:
  PRECOMPUTED_PROPOSAL_TOPK_TEST: 1000
  PRECOMPUTED_PROPOSAL_TOPK_TRAIN: 2000
  PROPOSAL_FILES_TEST: []
  PROPOSAL_FILES_TRAIN: []
  TRAIN:
  - openvocab_coco_2017_train_panoptic_with_sem_seg
  TEST:
  - openvocab_ade20k_panoptic_val

INPUT:
  DATASET_MAPPER_NAME: sa1b
  FEW_SHOT_JSON:
  - ""
  IMG_SIZE: 1024
  CROP_SIZE: 1024
  MIN_SCALE: 0.8
  MAX_SCALE: 1.2
  MIN_AREA_RATIO: 0.001
  MAX_AREA_RATIO: 0.8
  COLOR_AUG_SSD: true
  CROP:
    ENABLED: false
    SINGLE_CATEGORY_MAX_AREA: 1.0
    SIZE:
    - 0.9
    - 0.9
    TYPE: relative_range
  FORMAT: RGB
  MASK_FORMAT: polygon
  MAX_SIZE_TEST: 1333
  MAX_SIZE_TRAIN: 1333
  MIN_SIZE_TEST: 800
  MIN_SIZE_TRAIN:
  - 800
  MIN_SIZE_TRAIN_SAMPLING: choice
  RANDOM_FLIP: horizontal
  SIZE_DIVISIBILITY: -1

MODEL:
  META_ARCHITECTURE: UniOVSeg_S1
  BACKBONE:
    FREEZE_AT: 0
    NAME: CLIP
  DEVICE: cuda
  KEYPOINT_ON: false
  LOAD_PROPOSALS: false
  MASK_ON: false
  PIXEL_MEAN:
  - 122.7709383
  - 116.7460125
  - 104.09373615
  PIXEL_STD:
  - 68.5005327
  - 66.6321579
  - 70.32316305
  OVSEG:
    CLIP_MODEL_NAME: convnext_large_d_320
    CLIP_PRETRAINED_WEIGHTS: null
    PROMPT_ENCODER_NAME: PromptEncoder
    PIXEL_DECODER_NAME: MSDeformAttnPixelDecoder
    TRANSFORMER_ENC_LAYERS: 6
    COMMON_STRIDE: 4
    TRANSFORMER_DECODER_NAME: MultiScaleMaskDecoder
    TRANSFORMER_IN_FEATURE: multi_scale_pixel_decoder
    DEC_LAYERS: 10
    MASK_DIM: 256
    CONVS_DIM: 256
    EMBED_DIM: 256
    CLIP_DIM: 1536
    NHEADS: 8
    DIM_FEEDFORWARD: 2048
    DROPOUT: 0.0
    PRE_NORM: false
    NORM: GN
    ENFORCE_INPUT_PROJ: false
    NUM_MASKS: 4
    CRITERION_SEG: Many2ManySetCriterion
    CRITERION_ALIGN: MaskTextAlignCriterion
    MASK_WEIGHT: 2.0
    DICE_WEIGHT: 1.0
    IOU_WEIGHT: 1.0
    ALIGN_WEIGHT: 1.0
    MATCHER_NUM_POINTS: 6000
    TRAIN_NUM_POINTS: 12544
    OVERSAMPLE_RATIO: 3.0
    IMPORTANCE_SAMPLE_RATIO: 0.75
    LOSS_TOPK: 1.0
    SEM_SEG_POSTPROCESSING_BEFORE_INFERENCE: true
    PTS_PER_SIDE:
    - 10
    - 10
    SIZE_DIVISIBILITY: 32
    DEEP_SUPERVISION: true
    TEST:
      PTS_PER_SIDE:
      - 20
      - 20
      SEMANTIC_ON: false
      INSTANCE_ON: false
      PANOPTIC_ON: false
      MASKCLS_ON: false
      AUTOLABEL_ON: true
      AUTOLABEL_SAVE: false
      AUTOLABEL_TYPE: panoptic-point
      OBJECT_MASK_THRESHOLD: 0.7
      OVERLAP_THRESHOLD: 0.4
  WEIGHTS: ''

SOLVER:
  IMS_PER_BATCH: 56
  BASE_LR: 0.0001
  WARMUP_FACTOR: 1.0
  WARMUP_ITERS: 10
  WARMUP_METHOD: linear
  MAX_ITER: 110000
  STEPS:
  - 93500
  - 104500
  CHECKPOINT_PERIOD: 5000
  LR_SCHEDULER_NAME: WarmupMultiStepLR
  WEIGHT_DECAY: 0.05
  WEIGHT_DECAY_BIAS: null
  WEIGHT_DECAY_EMBED: 0.0
  WEIGHT_DECAY_NORM: 0.0
  AMP:
    ENABLED: true
  BACKBONE_MULTIPLIER: 0.1
  BASE_LR_END: 0.0
  BIAS_LR_FACTOR: 1.0
  CLIP_GRADIENTS:
    CLIP_TYPE: full_model
    CLIP_VALUE: 1.0
    ENABLED: true
    NORM_TYPE: 2.0
  GAMMA: 0.1
  MOMENTUM: 0.9
  NESTEROV: false
  NUM_DECAYS: 3
  OPTIMIZER: ADAMW
  POLY_LR_CONSTANT_ENDING: 0.0
  POLY_LR_POWER: 0.9
  REFERENCE_WORLD_SIZE: 0
  RESCALE_INTERVAL: false

VERSION: 2
VIS_PERIOD: 0